name: FindMe
version: 2.1.2-SNAPSHOT
main: de.greensurvivors.findme.FindMe
api-version: 1.21
authors: [ Feuerreiter ]
website: greensurvivors.de

commands:
  findme:
    aliases:
      - fm
    description: All find me commands.
