name: FindMe
version: 2.1.0-SNAPSHOT
main: de.greensurvivors.findme.FindMe
api-version: 1.19
authors: [ Feuerreiter ]
website: greensurvivors.de

commands:
  findme:
    aliases:
      - fm
    description: All find me commands.
