name: FindMe
version: $version
main: de.greensurvivors.findme.FindMe
api-version: '$mcVersion'
authors: [ Feuerreiter ]
website: greensurvivors.de

commands:
  findme:
    aliases:
      - fm
    description: All find me commands.
